[package]
name = "haloumi-test-circuits"
categories = {workspace = true}
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
rust-version = {workspace = true}
readme = "README.md"
repository = {workspace = true}
license-file = {workspace = true}
keywords = {workspace = true}
publish = false

[dependencies.midnight-proofs]
git = "https://github.com/Veridise/midnight-zk.git"
default-features = false
features = [
    "circuit-params",
    "committed-instances",
    "region-groups"
]

[dependencies]
ff = {workspace = true}
anyhow = "1"
