[package]
name = "haloumi-ir-gen"
description = "IR generation step of the haloumi lowering pipeline."
categories = {workspace = true}
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
rust-version = {workspace = true}
readme = "README.md"
repository = {workspace = true}
license-file = {workspace = true}
keywords = {workspace = true}

[dependencies]
haloumi-core = { path = "../core", version = "0.5.5"}
haloumi-ir = { path = "../ir", version = "0.5.5"}
haloumi-synthesis = { path = "../synthesis", version = "0.5.5" }
ff.workspace = true
log.workspace = true
thiserror.workspace = true
