[package]
name = "haloumi-midnight-integration"
categories = {workspace = true}
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
rust-version = {workspace = true}
readme = "README.md"
repository = {workspace = true}
license-file = {workspace = true}
keywords = {workspace = true}
publish = false

[dependencies]
haloumi-core = { path = "../../core", version = "0.5.3" }
ff = {workspace = true }

[dependencies.midnight-proofs]
git = "https://github.com/Veridise/midnight-zk.git"
default-features = false
features = [
    "circuit-params",
    "committed-instances",
    "region-groups"
]
