[package]
name = "haloumi-zcash-test-circuits"
categories = {workspace = true}
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
rust-version = {workspace = true}
readme = "README.md"
repository = {workspace = true}
license-file = {workspace = true}
keywords = {workspace = true}
publish = false

[dependencies.halo2_proofs]
git = "https://github.com/project-llzk/halo2.git"
branch = "haloumi-integration"
default-features = false
features = [
    "region-groups",
    "haloumi"
]

[dependencies]
ff = {workspace = true}
anyhow = "1"


