[package]
name = "haloumi-mdnt-test-circuits"
categories = {workspace = true}
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
rust-version = {workspace = true}
readme = "README.md"
repository = {workspace = true}
license-file = {workspace = true}
keywords = {workspace = true}
publish = false

[dependencies.midnight-proofs]
workspace = true

[dependencies]
ff = {workspace = true}
anyhow = "1"
haloumi-integration = { path = "../../integration", optional = true }
haloumi-ir = { path = "../../ir", optional = true }

[features]
extraction = [
    "midnight-proofs/extraction",
    "dep:haloumi-integration",
    "dep:haloumi-ir",
]
